name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: start containers
        run: docker-compose up -detach

      - name: wait for containers to be ready
        run: sleep 5s
        shell: bash

      - name: run migrations
        run: docker compose exec api npm run db-migrations:up

      - name: run tests on the api
        run: docker-compose exec -T api npm test

      - name: run tests on the client
        run: docker-compose exec -T client npm test


